import type { APIRoute } from 'astro';
import { SITE } from '../data/site';

/** Web app manifest (brief Polish P.10). The icons are generated by scripts/gen-brand.mjs. */
export const GET: APIRoute = () =>
  new Response(
    JSON.stringify({
      name: SITE.defaultTitle,
      short_name: SITE.name,
      start_url: '/',
      scope: '/',
      display: 'standalone',
      background_color: '#ffffff',
      theme_color: SITE.themeColor,
      lang: 'ko',
      icons: [
        { src: '/brand/icon-192.png', sizes: '192x192', type: 'image/png' },
        { src: '/brand/icon-512.png', sizes: '512x512', type: 'image/png' },
        { src: '/brand/icon-maskable-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
      ],
    }),
    { headers: { 'Content-Type': 'application/manifest+json' } },
  );
