// Builds the "UI" Pretendard subset: every character used in src/ (pages, data, generated license
// texts) plus printable ASCII, cut from the variable font and preloaded on every page.
// Why: the full dynamic subset needs ~13 font files (~330 KB) for the landing page alone, which
// pushed mobile LCP past 3 s. The UI subset is one preloaded file (~100 KB) and renders the same.
// Characters outside it (for example Korean file names on tool pages) fall back to the official,
// unmodified dynamic subset ("Pretendard Variable"), which the tool loads on demand.
// OFL 1.1: this subset is a Modified Version, so it must not use the Reserved Font Name
// "Pretendard". Its name table and CSS family are renamed to "Anolim UI Sans"; the copyright and
// license records stay, and /licenses/ carries the full OFL text.
import fontverter from 'fontverter';
import subsetFont from 'subset-font';
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { readNames, renameFont } from './font-rename.mjs';

export const UI_FAMILY = 'Anolim UI Sans';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const src = join(root, 'src');
const outDir = join(src, 'generated');

const texts = [];
const walk = (dir) => {
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const p = join(dir, e.name);
    if (e.isDirectory()) walk(p);
    else if (/\.(astro|ts|json|css)$/.test(e.name)) texts.push(readFileSync(p, 'utf8'));
  }
};
walk(src);

const codepoints = new Set();
for (const ch of texts.join('')) {
  const cp = ch.codePointAt(0);
  if (cp >= 0x20) codepoints.add(cp);
}
for (let cp = 0x20; cp < 0x7f; cp++) codepoints.add(cp);
// Punctuation used in generated UI strings (progress, separators, quotes).
for (const ch of '…·—–‘’“”©') codepoints.add(ch.codePointAt(0));

const sorted = [...codepoints].sort((a, b) => a - b);
const text = String.fromCodePoint(...sorted);
const font = readFileSync(join(root, 'node_modules', 'pretendard', 'dist', 'web', 'variable', 'woff2', 'PretendardVariable.woff2'));
const subset = await subsetFont(font, text, { targetFormat: 'truetype' });
const renamed = renameFont(subset, 'Pretendard', UI_FAMILY);
const names = readNames(renamed);
const leaked = Object.entries(names).filter(([id, v]) => ![0, 7, 13, 14].includes(Number(id)) && /Pretendard/i.test(v));
if (leaked.length) throw new Error(`gen-ui-font: reserved name left in name IDs ${leaked.map(([id]) => id).join(', ')}`);
const woff2 = await fontverter.convert(Buffer.from(renamed), 'woff2', 'truetype');

// unicode-range as merged runs, so the browser knows exactly which characters this face covers.
const ranges = [];
for (const cp of sorted) {
  const last = ranges[ranges.length - 1];
  if (last && cp === last[1] + 1) last[1] = cp;
  else ranges.push([cp, cp]);
}
const hex = (n) => n.toString(16);
const unicodeRange = ranges.map(([a, b]) => (a === b ? `U+${hex(a)}` : `U+${hex(a)}-${hex(b)}`)).join(', ');

mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, 'anolim-ui.woff2'), woff2);
writeFileSync(
  join(outDir, 'anolim-ui.css'),
  `/* Generated by scripts/gen-ui-font.mjs. "${UI_FAMILY}" is a subset of Pretendard, (c) 2021 Kil Hyung-jin,
   with Reserved Font Name Pretendard, SIL Open Font License 1.1 (see /licenses/). */
@font-face {
  font-family: '${UI_FAMILY}';
  font-style: normal;
  font-display: swap;
  font-weight: 45 920;
  src: url('./anolim-ui.woff2') format('woff2-variations');
  unicode-range: ${unicodeRange};
}
`,
);
console.log(`gen-ui-font: ${sorted.length} characters, ${(woff2.length / 1024).toFixed(1)} KiB, font name "${names[4]}"`);
