// Builds the "UI" Pretendard subset: every character used in src/ (pages, data, generated license
// texts) plus printable ASCII, cut from the variable font as four static weight instances; 400 and 800
// are preloaded on every page.
// Why: the full dynamic subset needs ~13 font files (~330 KB) for the landing page alone, which
// pushed mobile LCP past 3 s. The UI subset is one preloaded file (~100 KB) and renders the same.
// Characters outside it (for example Korean file names on tool pages) fall back to the official,
// unmodified dynamic subset ("Pretendard Variable"), which the tool loads on demand.
// OFL 1.1: this subset is a Modified Version, so it must not use the Reserved Font Name
// "Pretendard". Its name table and CSS family are renamed to "Anolim UI Sans"; the copyright and
// license records stay, and /licenses/ carries the full OFL text.
import fontverter from 'fontverter';
import subsetFont from 'subset-font';
import { mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { renameFont, reservedNameProblems } from './font-rename.mjs';

const UI_FAMILY = 'Anolim UI Sans';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const src = join(root, 'src');
const outDir = join(src, 'generated');

const texts = [];
const walk = (dir) => {
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const p = join(dir, e.name);
    if (e.isDirectory()) walk(p);
    else if (/\.(astro|ts|json|css)$/.test(e.name)) texts.push(readFileSync(p, 'utf8'));
  }
};
walk(src);

const codepoints = new Set();
for (const ch of texts.join('')) {
  const cp = ch.codePointAt(0);
  if (cp >= 0x20) codepoints.add(cp);
}
for (let cp = 0x20; cp < 0x7f; cp++) codepoints.add(cp);
// Punctuation used in generated UI strings (progress, separators, quotes).
for (const ch of '…·—–‘’“”©') codepoints.add(ch.codePointAt(0));

const sorted = [...codepoints].sort((a, b) => a - b);
const text = String.fromCodePoint(...sorted);
const font = readFileSync(join(root, 'node_modules', 'pretendard', 'dist', 'web', 'variable', 'woff2', 'PretendardVariable.woff2'));

// Static instances (Polish P.12): WebKit ignores the variation axis of a variable face, so every weight the
// CSS uses gets its own fully instanced face (no fvar). check-dist rejects any other weight in the CSS.
const UI_WEIGHTS = [400, 600, 700, 800];
// Only the OpenType features browsers apply by default (HarfBuzz's horizontal defaults). The CSS enables no
// other feature, so rendering is unchanged, and the alternates (ss01…, case, sups, aalt) no longer ship:
// about 20 % smaller per instance, which keeps the four faces inside the 170 KB budget.
const KEEP_FEATURES = ['abvm', 'blwm', 'ccmp', 'locl', 'mark', 'mkmk', 'rlig', 'calt', 'clig', 'curs', 'dist', 'kern', 'liga', 'rclt'];

// unicode-range as merged runs, so the browser knows exactly which characters this face covers.
const ranges = [];
for (const cp of sorted) {
  const last = ranges[ranges.length - 1];
  if (last && cp === last[1] + 1) last[1] = cp;
  else ranges.push([cp, cp]);
}
const hex = (n) => n.toString(16);
const unicodeRange = ranges.map(([a, b]) => (a === b ? `U+${hex(a)}` : `U+${hex(a)}-${hex(b)}`)).join(', ');

mkdirSync(outDir, { recursive: true });
for (const f of readdirSync(outDir)) if (/^anolim-ui(-\d+)?\.(woff2|css)$/.test(f)) rmSync(join(outDir, f));
const faces = [];
const sizes = [];
for (const weight of UI_WEIGHTS) {
  let subset;
  try {
    subset = await subsetFont(font, text, { targetFormat: 'truetype', variationAxes: { wght: weight }, keepFeatures: KEEP_FEATURES });
  } catch (err) {
    // Never fall back to the variable face silently (brief P.12 flag).
    throw new Error(`gen-ui-font: instancing wght=${weight} failed: ${err instanceof Error ? err.message : err}`);
  }
  const renamed = renameFont(subset, 'Pretendard', UI_FAMILY);
  // Every record on every platform, plus a raw byte scan of the name table (OFL Reserved Font Name).
  const leaked = reservedNameProblems(renamed, 'Pretendard');
  if (leaked.length) throw new Error(`gen-ui-font: reserved name "Pretendard" left in the ${weight} instance: ${leaked.join('; ')}`);
  const woff2 = await fontverter.convert(Buffer.from(renamed), 'woff2', 'truetype');
  const file = `anolim-ui-${weight}.woff2`;
  writeFileSync(join(outDir, file), woff2);
  sizes.push(`${weight} ${(woff2.length / 1024).toFixed(1)} KiB`);
  faces.push(`@font-face {
  font-family: '${UI_FAMILY}';
  font-style: normal;
  font-display: swap;
  font-weight: ${weight};
  src: url('./${file}') format('woff2');
  unicode-range: ${unicodeRange};
}`);
}
writeFileSync(
  join(outDir, 'anolim-ui.css'),
  `/* Generated by scripts/gen-ui-font.mjs. "${UI_FAMILY}" is a subset of Pretendard, (c) 2021 Kil Hyung-jin,
   with Reserved Font Name Pretendard, SIL Open Font License 1.1 (see /licenses/). Static instances at
   ${UI_WEIGHTS.join(', ')} (no variation axes). */
${faces.join('\n')}
`,
);
console.log(`gen-ui-font: ${sorted.length} characters, ${sizes.join(', ')}, font name "${UI_FAMILY}"`);
